all:
  metas:
    title:     hera - Suppliers
  components:
    searchForm: [search, supplierForm]
    
indexSuccess:
  stylesheets: [ /sfFormExtraPlugin/css/jquery.autocompleter.css ]
  javascripts:
    - core/table.js
    
editSuccess:
  javascripts:
    - invoice
