all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=siwapp'
      username: 'siwapp'
      password: '3ZqxybWATGB59uvL'

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=siwapp_test'
      username: 'siwapp'
      password: '3ZqxybWATGB59uvL'
