all:
  urls:
    include: ['payments', 'search']
    variables:
      editRow:          invoices/edit
      calculateInvoice: common/calculate
      checkProductsStock: common/checkProductsStock
      printHtml:        @invoices_print?action=print
      printPdf:         @invoices_print?action=pdf
      export:           @invoices_export
      remesar:          @invoices_remesar
      remesarsepa:      @invoices_remesarsepa
