# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

all:
  is_secure: on
  
index:
  credentials: can_access_users
  
new:
  credentials: can_create_users
  
edit:
  credentials: can_edit_users
  
delete:
  credentials: can_delete_users