all:
  metas:
    title:     hera - Users
  components:
    searchForm: [search, userForm]
    
indexSuccess:
  stylesheets: [ /sfFormExtraPlugin/css/jquery.autocompleter.css ]
  javascripts:
    - core/table.js
editSuccess:
  javascripts:
    - invoice.js

